name: Update Starred Repositories

permissions: write-all

on:
  schedule:
    - cron: '5 4 * * *'   # Run daily at 4:05 AM
  workflow_dispatch:      # Allow manual trigger

jobs:
  update-stars:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Update README with Starred Repositories
        uses: mxvsh/starkit@v1.3.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-username: ${{ github.actor }}
